name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ec2-54-204-176-241.compute-1.amazonaws.com
          REMOTE_USER: ubuntu
          TARGET: /var/www/indybms

      - name: Start Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ec2-54-204-176-241.compute-1.amazonaws.com
          username: ubuntu
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
          cd /var/www/indybms
          npm install
          npm start
